version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=bit64
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin@@1234
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=bit64
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin@@1234
    depends_on:
      - db
