# Generated by Django 4.0.1 on 2022-01-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poduct',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
