# Generated by Django 4.0.1 on 2022-01-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_rename_poduct_product_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prise',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
